
from lxml import etree
from datetime import datetime
import xml.etree.ElementTree as ET
import jinja2 as jja2
import logging as log
import subprocess as sp
import os
import sys
import shutil
import zipfile
import re
import platform
import random, string
import struct


def clean_temporary(self):
    temporary = ['buildlog.txt', 'dsin.txt', 'dslog.txt', 'dymosim', 'request.',
                 'status.', 'dsmodel.c', 'dsfinal.txt', 'dsmodel_fmuconf.h', 'fmiModelIdentifier.h']
    for fil in temporary:
        if os.path.isfile(fil):
            os.remove(fil)
    # FMU folders generated by Dymola
    DymFMU_tmp = ['~FMUOutput', '.FMUOutput',
                  'DymosimDll32', 'DymosimDll64']
    for fol in DymFMU_tmp:
        if os.path.isdir(fol):
            shutil.rmtree(fol)


    # Delete any files with extension in the list
    import glob
    for ext in ['*.c', '*.h', '*.o', '*.dll',
                '*.makefile', '*.libs', '*.json',
                '*.exe', '*.exp', '*.lib']:
        filelist = glob.glob(ext)
        for f in filelist:
            os.remove(f)