name: Library Build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        build-version: [v1.5.9.0]
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Cython
        python -m pip install --user --upgrade setuptools wheel

    - name: Build Library
      run: |
        python setup.py sdist bdist_wheel
      working-directory: dev/Package/fmup

    - name: Archive production
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dev/Package/fmup/dist